Fix build error on main caused by a missing symbol
```
/FoundationInternationalization/Calendar/Calendar_Enumerate.swift:370:21: error: value of type 'Date' has no member 'isValidForEnumeration'
        guard start.isValidForEnumeration else {
              ~~~~~ ^~~~~~~~~~~~~~~~~~~~~
error: fatalError
```